from typing import Protocol, runtime_checkable

from alpaca.trading.models import Asset, Order, Position, TradeAccount


@runtime_checkable
class Broker(Protocol):
    def get_account(self) -> TradeAccount: ...
    def get_positions(self) -> list[Position]: ...
    def get_open_orders(self) -> list[Order]: ...
    def get_asset(self, ticker: str) -> Asset: ...
    def submit_order(self, ticker: str, side: str, qty: float, order_type: str = "market") -> Order: ...
    def cancel_order(self, order_id: str) -> None: ...
