from datetime import date
from typing import Protocol, runtime_checkable

from alpaca.trading.models import Asset, Order, Position, TradeAccount


@runtime_checkable
class Broker(Protocol):
    def get_account(self) -> TradeAccount: ...
    def get_positions(self) -> list[Position]: ...
    def get_open_orders(self) -> list[Order]: ...
    def get_asset(self, ticker: str) -> Asset: ...
    def get_order(self, order_id: str) -> Order: ...
    def list_orders(self, *, status: str = "all", after: str | None = None, limit: int = 100) -> list[Order]: ...
    def submit_order(self, ticker: str, side: str, qty: float, order_type: str = "market", client_order_id: str | None = None) -> Order: ...
    def cancel_order(self, order_id: str) -> None: ...
    def get_sod_equity(self, date: date) -> float: ...
